### ISSUE TITLE
Possibly missed committing Gelatin.Core.Font and Fill?

### ISSUE THREAD

**Issue by cies** [schell/gelatin#4]
I get a compile error on a clean checkout of master:

    setup-Simple-Cabal-1.22.4.0-ghc-7.10.2: can't find source for
    Gelatin/Core/Fill in src,

**Comment by schell** [comment]
Ah, yes - I messed a bunch of stuff up with a current refactor, which apparently isn't all contained within the `fill_and_texture` branch. 

If you'd like to play around I'd suggest using commit [3e2f981](https://github.com/schell/gelatin/commit/3e2f981e40767284014a99a79e09ce94d30d4c7f) at least until I merge `fill_and_texture`.

**Comment by schell** [comment]
@cies - please let me know if the new `master` compiles for you.

**Comment by cies** [comment]
It did not. You seem to use a version of `sdl2` that I do not have; this fails build on `gelatin-sdl2`.

This is the error.

    gelatin/gelatin-sdl2/src/Gelatin/SDL2.hs:48:30: Not in scope: ‘glGetDrawableSize’

I found `glGetDrawableSize` from `SDL2.Raw.Video`, but that needs some pointer juggling, which I suppose you have an improved version of `sdl2` for in your the stack.yaml as shown here:

```
flags: {}
extra-package-dbs: []
packages: 
- '.'
- '../gelatin-core'
- '../gelatin-picture'
- '../gelatin-gl'
- '../../sdl2'
- location:
    git: https://github.com/schell/renderable.git
    commit: 743ea68c91daeb4c3000f3c0ce2c73fbac02cacc
- location:
    git: https://github.com/schell/FontyFruity
    commit: 99c143ebb569c286aa5252587923f8c34423e969
#extra-deps:
#- sdl2-2.1.1
resolver: lts-5.2
```

After some digging I found your PR on the `sdl2`. Mr Kmett chiming in et al. :) 

From there it was a small fix to get it to build. Namely this fix in some stack.yaml:

     - location:
        git: https://github.com/schell/sdl2
        commit: b3e8c9cb707ca45cf443b5103c5fd6dff1bb1fd3

I keep a stack.yaml at the top-level. Since I use a different LTS (not feeling like a full recompile).

Since I expect the fix to be in sdl2 soon, I'll not prepare a PR.
